fin = open("celulas.txt", "rt")
fout = open("celulas.yaml", "wt")
for line in fin:
    fout.write("apiVersion: backstage.io/v1alpha1\n")
    fout.write("kind: System\n")
    fout.write("metadata:\n")
    fout.write("\tname: " + line)
    fout.write("\tdescription: " + line)
    fout.write("spec:\n")
    fout.write("\towner: gobierno-it\n")
    fout.write("\tdomain: plataformas\n")
    fout.write("---\n")
fin.close()
fout.close()
