fin = open("k8s.txt", "rt")
fout = open("k8s.yaml", "wt")
for line in fin:
    fout.write("apiVersion: backstage.io/v1alpha1\n")
    fout.write("kind: Resource\n")
    fout.write("metadata:\n")
    fout.write("   name: " + line)
    fout.write("   description: " + line)
    fout.write("   title: " + line)
    fout.write("spec:\n")
    fout.write("   type: k8s\n")
    fout.write("   owner: gobierno-it\n")
    fout.write("---\n")
fin.close()
fout.close()
