fin = open("legacy.txt", "rt")
fout = open("legacy.yaml", "wt")
for line in fin:
    fout.write("apiVersion: backstage.io/v1alpha1\n")
    fout.write("kind: Component\n")
    fout.write("metadata:\n")
    fout.write("\tname: " + line)
    fout.write("\tdescription: " + line)
    fout.write("spec:\n")
    fout.write("\ttype: legacy\n")
    fout.write("\towner: gobierno-it\n")
    fout.write("---\n")
fin.close()
fout.close()