apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: tren-aplicaciones
   description: tren-aplicaciones
   title: tren-aplicaciones
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: tren-shared-services-e-infraestructura
   description: tren-shared-services-e-infraestructura
   title: tren-shared-services-e-infraestructura
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: producto-b2b
   description: producto-b2b
   title: producto-b2b
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: segmento-b2b
   description: segmento-b2b
   title: segmento-b2b
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: cuentas-corporativas
   description: cuentas-corporativas
   title: cuentas-corporativas
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: alianzas-y-proyectos-estrategicos
   description: alianzas-y-proyectos-estrategicos
   title: alianzas-y-proyectos-estrategicos
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: coe-ingenieria
   description: coe-ingenieria
   title: coe-ingenieria
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: segmento-b2c
   description: segmento-b2c
   title: segmento-b2c
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: prepago
   description: prepago
   title: prepago
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: logistica-y-terminales
   description: logistica-y-terminales
   title: logistica-y-terminales
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: tren-propuesta-de-valor
   description: tren-propuesta-de-valor
   title: tren-propuesta-de-valor
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: tren-e-commerce
   description: tren-e-commerce
   title: tren-e-commerce
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: tren-e-care
   description: tren-e-care
   title: tren-e-care
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: coe-data-y-analitica
   description: coe-data-y-analitica
   title: coe-data-y-analitica
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: canales-servicios-b2c
   description: canales-servicios-b2c
   title: canales-servicios-b2c
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: tren-canales-comerciales-b2c
   description: tren-canales-comerciales-b2c
   title: tren-canales-comerciales-b2c
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: tren-fareco
   description: tren-fareco
   title: tren-fareco
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: coe-comunicaciones
   description: coe-comunicaciones
   title: coe-comunicaciones
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: coe-desarrollo
   description: coe-desarrollo
   title: coe-desarrollo
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: coe-cdg
   description: coe-cdg
   title: coe-cdg
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: coe-de-riesgo-y-seguridad
   description: coe-de-riesgo-y-seguridad
   title: coe-de-riesgo-y-seguridad
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: coe-legal
   description: coe-legal
   title: coe-legal
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: coe-marcomms
   description: coe-marcomms
   title: coe-marcomms
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: direccion-operaciones-redes
   description: direccion-operaciones-redes
   title: direccion-operaciones-redes
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: operaciones-redes
   description: operaciones-redes
   title: operaciones-redes
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: ceo
   description: ceo
   title: ceo
spec:
   owner: gobierno-it
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
   name: plataformas
   description: plataformas
   title: plataformas
spec:
   owner: gobierno-it
---
