fin = open("tren.txt", "rt")
fout = open("tren.yaml", "wt")
for line in fin:
    fout.write("apiVersion: backstage.io/v1alpha1\n")
    fout.write("kind: Domain\n")
    fout.write("metadata:\n")
    fout.write("   name: " + line)
    fout.write("   description: " + line)
    fout.write("   title: " + line)
    fout.write("spec:\n")
    fout.write("   owner: gobierno-it\n")
    fout.write("---\n")
fin.close()
fout.close()
