apiVersion: backstage.io/v1alpha1
kind: System
metadata:
   name: ServiciosDeIntegracionOpenShift
   title: Servicios de integración OpenShift
spec:
   owner: Cloud
   domain: ServiciosTransversalesDeIntegracion
