apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
   name: TrenAplicaciones
   description: Tren Aplicaciones
   tags:
    - tren
spec:
   type: team
   children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
   name: TrenSharedServiceseInfraestructura
   description: Tren Shared Services e Infraestructura
   tags:
    - tren
spec:
   type: team
   children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
   name: ProductoB2B
   description: Producto B2B
   tags:
    - tren
spec:
   type: team
   children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
   name: TrenPropuestadeValor
   description: Tren Propuesta de Valor
   tags:
    - tren
spec:
   type: team
   children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
   name: TrenE-commerce
   description: Tren E-commerce
   tags:
    - tren
spec:
   type: team
   children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
   name: TrenE-care
   description: Tren E-care
   tags:
    - tren
spec:
   type: team
   children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
   name: CoEDatayAnalitica
   description: CoE Data y Analitica
   tags:
    - tren
spec:
   type: team
   children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
   name: TrenFareco
   description: Tren Fareco
   tags:
    - tren
spec:
   type: team
   children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
   name: OperacionesRedes
   description: Operaciones Redes
   tags:
    - tren
spec:
   type: team
   children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
   name: Arquitectura
   description: Arquitectura
   tags:
    - tren
spec:
   type: team
   children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
   name: Cloud
   description: Cloud
   tags:
    - tren
spec:
   type: team
   children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
   name: Infraestructura
   description: Infraestructura
   tags:
    - tren
spec:
   type: team
   children: []
---
